create table market_briefings (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);