create table sim_archives (
  id bigint generated by default as identity primary key,
  start_date timestamp with time zone not null,
  end_date timestamp with time zone not null,
  final_balance numeric not null,
  total_pnl numeric not null,
  win_rate numeric not null,
  trade_count integer not null,
  best_trade text, -- e.g. "BTC +15%"
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);