-- 1. Table for Real-Time Terminal Logs
create table if not exists bot_logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  level text default 'info', -- 'info', 'success', 'error'
  message text not null,
  meta jsonb -- Store extra data like { coin: "BTC", rsi: 30 }
);

-- 2. Table for Market Intelligence (Briefings)
create table if not exists market_briefings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  sentiment_score numeric, -- -1 to 1
  summary text not null,
  key_narratives text[] -- Array of strings ['AI', 'Gaming']
);

-- 3. Enhance Trades Table with AI Data
alter table sim_trades add column if not exists ai_reasoning text;

alter table sim_trades add column if not exists ai_confidence text;

-- 4. Enable Realtime (Run this if you can, otherwise enable in Dashboard -> Database -> Replication)
begin;

drop publication if exists supabase_realtime;

create publication supabase_realtime for table bot_logs, sim_trades;

commit;