import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { useEffect, useState } from "react"
import { createClient } from "@supabase/supabase-js"
import { Sparkles, TrendingUp, TrendingDown, AlertCircle } from "lucide-react"

const supabase = createClient(
    import.meta.env.VITE_SUPABASE_URL,
    import.meta.env.VITE_SUPABASE_ANON_KEY
)

interface Briefing {
    sentiment_score: number;
    summary: string;
    key_narratives: string[];
    created_at: string;
}

export function DailyBriefingCard() {
    const [briefing, setBriefing] = useState<Briefing | null>(null)

    useEffect(() => {
        const fetch = async () => {
            const { data } = await supabase
                .from('market_briefings')
                .select('*')
                .order('created_at', { ascending: false })
                .limit(1)
                .single()
            if (data) setBriefing(data)
        }
        fetch()
    }, [])

    if (!briefing) return null;

    const sentimentColor = briefing.sentiment_score > 0 ? "text-green-400" : "text-red-400";
    const sentimentIcon = briefing.sentiment_score > 0 ? <TrendingUp className="h-5 w-5" /> : <TrendingDown className="h-5 w-5" />;
    
    // Interpret Score: -1 to 1
    const sentimentText = briefing.sentiment_score > 0.3 ? "Bullish" : briefing.sentiment_score < -0.3 ? "Bearish" : "Neutral";

    return (
        <Card className="h-full bg-gradient-to-r from-indigo-950/40 to-purple-950/40 border-purple-500/30 overflow-hidden relative flex flex-col">
            <div className="absolute top-0 right-0 p-4 opacity-10">
                <Sparkles className="h-32 w-32 text-purple-500" />
            </div>
            
            <CardHeader className="pb-2">
                <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                         <div className="p-2 bg-purple-500/20 rounded-lg">
                            <Sparkles className="h-5 w-5 text-purple-400" />
                         </div>
                         <CardTitle className="text-lg font-bold tracking-tight">Daily Strategist Brief</CardTitle>
                    </div>
                    <Badge variant="outline" className={`gap-1 ${sentimentColor} border-current`}>
                        {sentimentIcon}
                        {sentimentText} ({(briefing.sentiment_score * 100).toFixed(0)}%)
                    </Badge>
                </div>
            </CardHeader>
            <CardContent className="flex-1 flex flex-col">
                <div className="space-y-4 flex-1">
                    <p className="text-lg font-medium leading-relaxed text-slate-200">
                        "{briefing.summary}"
                    </p>
                    
                    <div className="flex flex-wrap gap-2 pt-2">
                        {briefing.key_narratives?.map((tag, i) => (
                            <Badge key={i} variant="secondary" className="bg-slate-800 hover:bg-slate-700">
                                #{tag}
                            </Badge>
                        ))}
                    </div>
                    
                    <div className="mt-auto text-xs text-muted-foreground flex flex-col gap-1 pt-2 border-t border-border/50">
                        <div className="flex items-center gap-1">
                            <AlertCircle className="h-3 w-3" />
                            Generated by AI Llama 3 • {new Date(briefing.created_at).toLocaleTimeString()}
                        </div>
                        <span className="text-[10px] opacity-70 italic">
                            *Algorithmic score based on last 24h keywords
                        </span>
                    </div>
                </div>
            </CardContent>
        </Card>
    )
}
